Repository RedHatProductSecurity/osim, pull requests merged in 2024-04, with the labels that each got.

#136 Add case for "My issues" on index page
  features/flaw_filter.feature
  features/pages/advanced_search_page.py
  features/pages/home_page.py
  features/steps/flaw_filter.py
  features/utils.py
Labels: QE

#161 Update features for sort flaws refinement
  features/flaw_list.feature
  features/pages/home_page.py
  features/steps/flaw_list.py
  features/utils.py
Labels: QE

#144 ✨ Give visual feedback for API keys being set
  src/components/Settings.vue
  src/components/__tests__/App.spec.ts
  src/components/__tests__/IssueQueue.spec.ts
  src/components/__tests__/Navbar.spec.ts
  src/stores/SettingsStore.ts
  src/stores/__tests__/SettingsStore.spec.ts
Labels: requires huddle

#156 📝 Contribution documents
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation

#141 ✨ Provide changelog modal
  .dockerignore
  package.json
  public/CHANGELOG.md
  src/App.vue
  src/assets/fonts/RedHatDisplayVFModified.woff2
  src/assets/fonts/RedHatMono-Italic-VariableFont_wght.ttf
  src/assets/fonts/RedHatMono-VariableFont_wght.ttf
  src/assets/fonts/RedHatTextVFModified.woff2
  src/components/ChangeLog.vue
  src/components/Settings.vue
  src/components/__tests__/App.spec.ts
  src/scss/bootstrap-overrides.scss
  vite.config.ts
  yarn.lock
Labels: requires huddle

#150 Revises Flaw validations
  CHANGELOG.md
  src/components/FlawForm.vue
  src/components/IssueFieldEmbargo.vue
  src/components/IssueQueue.vue
  src/components/Navbar.vue
  src/composables/useFlawModel.ts
  src/router/index.ts
  src/services/ApiKeyService.ts
  src/types/zodFlaw.ts
  src/utils/helpers.ts
Labels: requires huddle

#160 Fix/osidb 2375 refresh behavior
  CHANGELOG.md
  src/assets/main.css
  src/components/FlawForm.vue
  src/composables/service-helpers.ts
  src/composables/useFlawAttributionsModel.ts
  src/composables/useFlawModel.ts
Labels: requires huddle

#173 🐛 OSIDB-2458 Reference deletion wrong message
  CHANGELOG.md
  src/components/IssueFieldReferences.vue
  src/types/zodFlaw.ts
Labels: bug

#175 🐛 OSIDB-2459 Fix external url reference validation
  CHANGELOG.md
  src/types/zodFlaw.ts
Labels: bug

#185 Align UI changes in flaw create page
  features/pages/advanced_search_page.py
  features/pages/base.py
  features/pages/flaw_create_page.py
  features/pages/flaw_detail_page.py
  features/pages/home_page.py
  features/pages/login_page.py
  features/pages/settings_page.py
  features/steps/flaw_create.py
  features/utils.py
Labels: QE

#179 💄 OSIDB-2512: Show url on references links
  CHANGELOG.md
  src/components/IssueFieldReferences.vue
Labels: enhancement

#186 🩹 OSIDB-2562 Hide source column
  CHANGELOG.md
  src/components/FlawForm.vue
  src/components/IssueQueue.vue
  src/components/IssueQueueItem.vue
  src/components/IssueSearchAdvanced.vue
  src/components/__tests__/FlawForm.spec.ts
Labels: enhancement

#188 Change create flaw related test cases, use relative locators
  features/pages/base.py
  features/pages/flaw_create_page.py
  features/pages/flaw_detail_page.py
Labels: QE
