Repository RedHatProductSecurity/osim, pull requests merged in 2024-10, with the labels that each got.

#444 📝 Merge old unreleased updates with initial release
  CHANGELOG.md
Labels: documentation, internal

#447 🐛 OSIDB-3502: Correct emptiness button tooltips
  CHANGELOG.md
  src/components/IssueSearchAdvanced.vue
  src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap
Labels: bug

#448 🐛 Remove widget link on navbar
  src/components/Navbar.vue
Labels: bug, internal

#449 OSIDB-3423: Enable coverage on CI
  package.json
  src/components/__tests__/__snapshots__/FlawFormOwner.spec.ts.snap
  vitest.config.ts
  yarn.lock
Labels: config

#451 ✨ OSIDB-3371: Create a design for displaying History in OSIM
  .gitignore
  CHANGELOG.md
  src/components/FlawForm.vue
  src/components/FlawHistory.vue
  src/components/__tests__/FlawAlertsList.spec.ts
  src/components/__tests__/FlawHistory.spec.ts
  src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawHistory.spec.ts.snap
  src/constants/flawFields.ts
  src/services/FlawService.ts
  src/types/zodFlaw.ts
  src/utils/helpers.ts
  src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Labels: enhancement

#457 🐛 Fix flaw history validation issue
  src/types/zodFlaw.ts
Labels: bug, internal

#455 🐛 OSIDB-3533: Reset affects delegated resolution
  CHANGELOG.md
  src/components/FlawAffects.vue
Labels: bug

#456 update case:Search flaws with selected field and value =
  features/README.md
  features/advance_search.feature
  features/common_utils.py
  features/constants.py
  features/pages/advanced_search_page.py
  features/pages/flaw_detail_page.py
  features/steps/advance_search.py
  features/steps/flaw_create.py
  features/steps/flaw_detail.py
  features/utils.py
  scripts/run_automation_test.sh
Labels: QE

#464 📝 Release 2024.10.0
  CHANGELOG.md
Labels: internal

#460 add case for advance search: Sort search result by sortable fields in result table
  features/advance_search.feature
  features/pages/advanced_search_page.py
  features/pages/home_page.py
  features/steps/advance_search.py
  features/steps/flaw_list.py
  features/utils.py
Labels: QE

#465 🐛 OSIDB-3592: Bugzilla link overlap on flaw state promotion button
  CHANGELOG.md
  src/components/FlawForm.vue
  src/components/__tests__/FlawForm.spec.ts
  src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap
  src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Labels: bug

#461 OSIDB-3546: CVSS Section extension
  CHANGELOG.md
  eslint.config.mjs
  src/components/CvssCalculator.vue
  src/components/CvssExplainForm.vue
  src/components/CvssNISTForm.vue
  src/components/CvssSection.vue
  src/components/FlawAffects.vue
  src/components/FlawContributors.vue
  src/components/FlawForm.vue
  src/components/FlawFormOwner.vue
  src/components/IssueFieldEmbargo.vue
  src/components/IssueFieldState.vue
  src/components/__tests__/CvssNISTForm.spec.ts
  src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawFormOwner.spec.ts.snap
  src/components/__tests__/test-suite-helpers.ts
  src/components/widgets/LabelDiv.vue
  src/composables/__tests__/useFlawCvssScores.spec.ts
  src/composables/useFlawAffectsModel.ts
  src/composables/useFlawCvssScores.ts
  src/utils/helpers.ts
  src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Labels: enhancement
