Repository RedHatProductSecurity/osim, pull requests merged in 2024-06, with the labels that each got.

#247 Feature: Tracker's external links
  CHANGELOG.md
  src/components/AffectedOfferingForm.vue
  src/components/FlawForm.vue
  src/components/__tests__/AffectExpandableForm.spec.ts
  src/composables/useFlawModel.ts
  src/services/TrackerService.ts
Labels: enhancement

#239 Feature: Button to expand all affects
  CHANGELOG.md
  src/components/AffectedOfferings.vue
Labels: enhancement

#237 Task: Remap comments based on OSIDB changes
  CHANGELOG.md
  src/components/CveRequestForm.vue
  src/components/FlawComments.vue
  src/composables/useFlawModel.ts
  src/services/FlawService.ts
  src/types/zodFlaw.ts
Labels: bug

#253 Task: Lint rules update
  .eslintrc.json
  src/components/BootstrapLabelInputExample.vue
  src/components/CvssCalculator.vue
  src/components/Navbar.vue
  src/components/widgets/EditableDate.vue
  src/components/widgets/Toast.vue
Labels: config

#256 Feature: Internal jira comments + Comments section redesign
  .eslintrc.json
  .gitignore
  CHANGELOG.md
  Dockerfile
  build/entrypoint.d/20-osim-runtime-json.sh
  build/entrypoint.d/30-reverse-proxy.sh
  build/nginx-default.d-osim.conf
  docs/overview.md
  src/components/FlawComments.vue
  src/components/FlawForm.vue
  src/components/__tests__/AffectExpandableForm.spec.ts
  src/components/__tests__/FlawComments.spec.ts
  src/components/widgets/Tabs.vue
  src/composables/useFlawModel.ts
  src/composables/useInternalComments.ts
  src/services/JiraService.ts
  src/services/TrackerService.ts
  src/stores/osimRuntime.ts
  src/types/zodFlaw.ts
Labels: enhancement, config

#257 Task: Allow references without description
  CHANGELOG.md
  src/components/IssueFieldReferences.vue
  src/types/zodFlaw.ts
Labels: bug

#271 Fix OSIDB-2904: Unembargoed btn not shown
  src/components/FlawForm.vue
Labels: bug

#276 Fix failed cases for affects
  features/flaw_detail_embargo.feature
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#281 Minor update the order
  features/flaw_detail_embargo.feature
Labels: QE

#269 Task OSIDB-2790: Use timezone on public date
  CHANGELOG.md
  src/components/widgets/EditableDate.vue
Labels: enhancement

#286 Fix the failed cases for advance search
  features/advance_search.feature
  features/pages/advanced_search_page.py
  features/steps/advance_search.py
Labels: QE

#287 Add test case for filing tracker to jira with affectness is Affected
  features/flaw_detail_public.feature
  features/pages/base.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#292 Changelog: Release v2024-6-0 update
  CHANGELOG.md
Labels: documentation

#284 Task OSIDB-2912: Support private flaw comments
  CHANGELOG.md
  src/components/CveRequestForm.vue
  src/components/FlawComments.vue
  src/components/FlawForm.vue
  src/components/__tests__/FlawComments.spec.ts
  src/components/widgets/Tabs.vue
  src/composables/useFlawModel.ts
  src/composables/useInternalComments.ts
  src/services/FlawService.ts
Labels: enhancement

#307 Task OSIDB-3002: Disable private comment creation
  CHANGELOG.md
  src/components/FlawComments.vue
  src/views/FlawEditView.vue
Labels: bug

#310 add test cases for filing tracker to bz
  features/flaw_detail_public.feature
  features/pages/base.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#309 Fix failed case(except affects related) in flaw_detail_public.feature
  features/flaw_detail_public.feature
  features/pages/base.py
  features/pages/flaw_create_page.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_create.py
  features/steps/flaw_detail.py
  features/utils.py
Labels: QE

#316 Task OSIDB-3012: Enable private comments creation
  CHANGELOG.md
  src/components/FlawComments.vue
Labels: bug

#288 Fix OSIDB-2827: Flaw list text overlap
  CHANGELOG.md
  src/components/IssueQueue.vue
  src/components/IssueQueueItem.vue
  src/components/Navbar.vue
  src/components/__tests__/IssueQueue.spec.ts
Labels: bug

#306 OSIDB-2916: Add Contributors field
  CHANGELOG.md
  src/components/FlawContributors.vue
  src/components/FlawForm.vue
  src/components/__tests__/FlawContributors.spec.ts
  src/composables/__tests__/useJiraContributors.spec.ts
  src/composables/useJiraContributors.ts
  src/services/JiraService.ts
  src/types/zodJira.ts
Labels: enhancement

#311 Task OSIDB-2511: Unify cvss calculator fields
  CHANGELOG.md
  src/components/CvssCalculator.vue
  src/components/CvssExplainForm.vue
  src/components/FlawForm.vue
  src/components/__tests__/CvssCalculator.spec.ts
  src/components/__tests__/CvssExplainForm.spec.ts
  src/components/__tests__/FlawForm.spec.ts
  src/composables/useFlawCvssScores.ts
Labels: enhancement
