Repository RedHatProductSecurity/osim, pull requests merged in 2024-07, with the labels that each got.

#319 add testcase for create trackers for notaffected
  features/flaw_detail_public.feature
  features/pages/base.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#323 Fix OSIDB-3066: Refresh multiple created attributions
  CHANGELOG.md
  src/composables/useFlawAttributionsModel.ts
Labels: bug

#327 Update flaw creation scenario to check alert
  features/pages/base.py
  features/pages/flaw_detail_page.py
  features/pages/home_page.py
  features/steps/common_steps.py
  features/steps/flaw_create.py
Labels: QE

#328 Add test case for filed trackers list
  features/constants.py
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#330 Enforce jira link on pull requests
  .github/pull_request_template.md
  .github/workflows/jira.yaml
Labels: internal

#299 Style OSIDB-2005: UI Space optimization
  CHANGELOG.md
  src/components/AffectExpandableForm.vue
  src/components/AffectedOfferings.vue
  src/components/AffectsTrackers.vue
  src/components/CvssCalculator.vue
  src/components/CvssExplainForm.vue
  src/components/CvssNISTForm.vue
  src/components/FlawAlert.vue
  src/components/FlawAlertsList.vue
  src/components/FlawAlertsSection.vue
  src/components/FlawComments.vue
  src/components/FlawForm.vue
  src/components/FlawFormOwner.vue
  src/components/IssueFieldReferences.vue
  src/components/IssueFieldState.vue
  src/components/__tests__/FlawForm.spec.ts
  src/components/widgets/EditableList.vue
  src/components/widgets/LabelDiv.vue
  src/components/widgets/LabelEditable.vue
  src/components/widgets/LabelInput.vue
  src/components/widgets/LabelSelect.vue
  src/components/widgets/LabelStatic.vue
  src/components/widgets/LabelTagsInput.vue
  src/components/widgets/LabelTextarea.vue
  src/components/widgets/TagsInput.vue
Labels: enhancement

#334 🔖 Increment version for v2024.7.0 release
  CHANGELOG.md
Labels: internal

#335 Add test case for contributors field
  features/flaw_detail_public.feature
  features/pages/base.py
  features/pages/flaw_detail_page.py
  features/pages/home_page.py
  features/steps/flaw_detail.py
  features/steps/flaw_list.py
Labels: QE

#336 Add testcases for select_deselect all trackers
  features/README.md
  features/constants.py
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#339 🐛 Fix OSIDB-3091: Internal comments creation fail on Chrome browser
  CHANGELOG.md
  build/entrypoint.d/30-reverse-proxy.sh
  src/services/JiraService.ts
Labels: bug

#338 🐛 OSIDB-3092: Remove duplicated loading spinner
  CHANGELOG.md
  src/components/IssueQueue.vue
Labels: bug

#329 Fix OSIDB-2905: Edited references not commited
  CHANGELOG.md
  src/components/widgets/EditableList.vue
Labels: bug

#346 fix public flaw edit cases
  features/flaw_create_embargo.feature
  features/flaw_create_public.feature
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE, internal

#344 Add testcase for file zstream tracker
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#350 fix failed test cases and add script to execute feature files by order
  features/advance_search.feature
  features/common_utils.py
  features/constants.py
  features/pages/advanced_search_page.py
  features/pages/flaw_create_page.py
  features/pages/flaw_detail_page.py
  features/pages/home_page.py
  features/quick_search.feature
  features/steps/advance_search.py
  features/steps/flaw_create.py
  features/steps/flaw_list.py
  features/steps/quick_search.py
  features/utils.py
  scripts/run_automation_test.sh
Labels: QE

#354 OSIDB-3154: Use a shallow watch
  src/composables/useFlawAffectsModel.ts
Labels: bug

#355 Update the autotest script to skip the affect cases
  features/flaw_detail_embargo.feature
  features/flaw_detail_public.feature
  scripts/run_automation_test.sh
Labels: QE

#359 fix failed test cases because of "Public Text[future]"
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE, internal

#358 Feature OSIDB-3138: Search non empty CVE description
  CHANGELOG.md
  src/components/IssueSearchAdvanced.vue
  src/components/Navbar.vue
  src/components/__tests__/FlawSearchView.spec.ts
  src/components/__tests__/IssueSearchAdvanced.spec.ts
  src/components/widgets/LabelCheckbox.vue
  src/composables/__tests__/useSearchParams.spec.ts
  src/composables/useFlawsFetching.ts
Labels: enhancement

#363 Release 2024.7.1
  CHANGELOG.md
Labels: internal

#365 🐛 Fix: Regression UI bug on textarea descriptions layout
  CHANGELOG.md
  src/components/widgets/LabelTextarea.vue
Labels: bug

#364 Add test case for advance search with cve description and cve descrip…
  features/steps/advance_search.py
Labels: QE, internal

#368 add test case for erase CVSSv3 field
  features/flaw_detail_public.feature
  features/page_factory_utils.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#366 📝 Update change log for release
  CHANGELOG.md
Labels: internal

#372 OSIDB-3189: Fix prop name
  src/components/FlawForm.vue
Labels: internal
