Repository RedHatProductSecurity/osim, pull requests merged in 2024-08, with the labels that each got.

#374 OSIDB-3233: Fix integration tests
  features/advance_search.feature
  features/environment.py
  features/flaw_detail_embargo.feature
  features/flaw_list.feature
  features/login.feature
  features/pages/flaw_create_page.py
  features/pages/login_page.py
  features/steps/login.py
  features/utils.py
  scripts/run_automation_test.sh
Labels: QE

#375 Fix the depends on OSIDB API for advance search
  features/advance_search.feature
  features/pages/advanced_search_page.py
  features/pages/flaw_detail_page.py
  features/steps/advance_search.py
  features/utils.py
Labels: QE

#285 Task: Unified comments model
  CHANGELOG.md
  src/components/FlawComments.vue
  src/components/FlawForm.vue
  src/components/__tests__/FlawComments.spec.ts
  src/components/__tests__/__snapshots__/FlawComments.spec.ts.snap
  src/composables/useFlawCommentsModel.ts
  src/composables/useFlawModel.ts
  src/composables/useInternalComments.ts
  src/constants/index.ts
  src/services/FlawService.ts
  src/services/JiraService.ts
  src/types/zodFlaw.ts
Labels: enhancement, internal

#382 OSIDB-3262: Remove historical affects validation
  CHANGELOG.md
  src/types/zodAffect.ts
Labels: bug

#385 ♻️ Allow WONTFIX affect resolution
  CHANGELOG.md
  src/types/zodAffect.ts
Labels: internal

#381 Fix failing test scenarios
  features/flaw_detail_embargo.feature
  features/flaw_detail_public.feature
  features/pages/base.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#388 Release 2024.7.3
  CHANGELOG.md
Labels: internal
