Repository RedHatProductSecurity/osim, pull requests merged in 2024-12, with the labels that each got.

#477 ✨ OSIDB-3562: Flaw history filtering
  CHANGELOG.md
  src/components/FlawHistory/FlawHistory.vue
  src/components/__tests__/FlawHistory.spec.ts
  src/components/__tests__/__snapshots__/FlawHistory.spec.ts.snap
  src/widgets/EditableDate/EditableDate.vue
Labels: enhancement

#515 📝 Release 2024.12.0
  CHANGELOG.md
Labels: internal

#516 📝 Remove duplicated items
  CHANGELOG.md
Labels: internal

#519 🐛 Fix cvss not created on new affects
  CHANGELOG.md
  src/composables/useFlawAffectsModel.ts
Labels: bug

#467 integration test: Sort search result by extended sortable field
  features/advance_search.feature
  features/pages/advanced_search_page.py
  features/pages/flaw_detail_page.py
  features/steps/advance_search.py
  features/steps/common_steps.py
  features/steps/flaw_create.py
  features/steps/flaw_detail.py
  features/utils.py
Labels: QE

#520 integration test:Filter trackers by Status field
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE
