Repository RedHatProductSecurity/osim, pull requests merged in 2024-09, with the labels that each got.

#371 OSIDB-2818: Affect section redesign
  CHANGELOG.md
  src/components/AffectExpandableForm.vue
  src/components/AffectedOfferingForm.vue
  src/components/AffectedOfferings.vue
  src/components/AffectsTrackers.vue
  src/components/FlawAffects.vue
  src/components/FlawForm.vue
  src/components/FlawTrackers.vue
  src/components/TrackerManager.vue
  src/components/__tests__/AffectExpandableForm.spec.ts
  src/components/__tests__/AffectedOfferings.spec.ts
  src/components/__tests__/AffectsTrackers.spec.ts
  src/components/__tests__/CvssExplainForm.spec.ts
  src/components/__tests__/FlawAffects.spec.ts
  src/components/__tests__/FlawAlertsList.spec.ts
  src/components/__tests__/FlawForm.spec.ts
  src/components/__tests__/FlawFormOwner.spec.ts
  src/components/__tests__/FlawSearchView.spec.ts
  src/components/__tests__/FlawTrackers.spec.ts
  src/components/__tests__/IndexView.spec.ts
  src/components/__tests__/IssueQueue.spec.ts
  src/components/__tests__/Navbar.spec.ts
  src/components/__tests__/SampleData.ts
  src/components/__tests__/__fixtures__/sampleFlawEmpty.json
  src/components/__tests__/__fixtures__/sampleFlawFull.json
  src/components/__tests__/__fixtures__/sampleFlawRequired.json
  src/components/__tests__/__snapshots__/FlawAffects.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawTrackers.spec.ts.snap
  src/components/__tests__/test-suite-helpers.ts
  src/components/widgets/Modal.vue
  src/composables/__tests__/usePagination.spec.ts
  src/composables/useFlawAffectsModel.ts
  src/composables/usePagination.ts
  src/composables/useTrackers.ts
  src/services/__tests__/FlawService.spec.ts
  src/stores/SettingsStore.ts
  src/stores/__tests__/SettingsStore.spec.ts
Labels: enhancement

#399 Fix assign to self test case not successfully assign current user to assignee field problem. Remove redundant code.
  features/pages/flaw_create_page.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_create.py
  features/steps/flaw_detail.py
Labels: QE

#397 ✨ Add query mode to advance search
  CHANGELOG.md
  src/components/IssueSearchAdvanced.vue
  src/components/QueryFilterGuide.vue
  src/components/__tests__/FlawSearchView.spec.ts
  src/components/__tests__/IssueSearchAdvanced.spec.ts
  src/composables/__tests__/useSearchParams.spec.ts
  src/composables/useSearchParams.ts
  src/views/FlawSearchView.vue
Labels: enhancement

#407 🐛 Affects CVSS CRUD operations
  CHANGELOG.md
  src/components/FlawAffects.vue
  src/components/FlawForm.vue
  src/components/FlawTrackers.vue
  src/components/__tests__/__snapshots__/FlawAffects.spec.ts.snap
  src/composables/useFlawAffectsModel.ts
  src/services/AffectService.ts
Labels: bug

#398 ✨ Support saving query filter on default user search
  CHANGELOG.md
  src/components/IssueQueue.vue
  src/components/__tests__/FlawSearchView.spec.ts
  src/components/__tests__/IndexView.spec.ts
  src/composables/useSearchParams.ts
  src/stores/SearchStore.ts
  src/views/FlawSearchView.vue
  src/views/IndexView.vue
Labels: enhancement

#408 Update add affect automation test case for affect redesign
  features/flaw_detail_embargo.feature
  features/flaw_detail_public.feature
  features/pages/advanced_search_page.py
  features/pages/base.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#413 🐛 Fix trackers refreshing after file
  src/components/FlawAffects.vue
  src/components/FlawForm.vue
  src/components/TrackerManager.vue
Labels: bug

#419 📝 Fix changelog after cherry-picked release
  CHANGELOG.md
Labels: internal

#420 🐛 OSIDB-3440: Fix tracker links
  CHANGELOG.md
  src/components/FlawTrackers.vue
  src/components/__tests__/FlawForm.spec.ts
  src/components/__tests__/__snapshots__/FlawAffects.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawTrackers.spec.ts.snap
  src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap
  src/services/TrackerService.ts
  src/stores/osimRuntime.ts
Labels: bug

#422 📝 Update changelog after v20204.9.1 hotfix release
  CHANGELOG.md
Labels: internal

#423 🐛 OSIDB-3443: Fix wrong column mapping on trackers table
  CHANGELOG.md
  src/components/FlawAffects.vue
  src/components/FlawTrackers.vue
  src/components/__tests__/FlawTrackers.spec.ts
  src/components/__tests__/__snapshots__/FlawAffects.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawTrackers.spec.ts.snap
Labels: bug, enhancement

#401 ✨ Multifields emptiness advanced search support
  CHANGELOG.md
  src/components/IssueSearchAdvanced.vue
  src/components/__tests__/IssueSearchAdvanced.spec.ts
  src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap
  src/composables/useFlawsFetching.ts
  src/stores/SearchStore.ts
  src/views/FlawSearchView.vue
  src/views/IndexView.vue
Labels: enhancement

#425 🐛 LabelCollapsible readonly error
  src/components/CvssExplainForm.vue
  src/components/FlawAffects.vue
  src/components/FlawAlert.vue
  src/components/FlawAlertsList.vue
  src/components/FlawAlertsSection.vue
  src/components/widgets/EditableList.vue
  src/components/widgets/LabelCollapsible.vue
Labels: bug

#416 ✨ Add aditional advance search result sorting fields
  CHANGELOG.md
  src/components/IssueSearchAdvanced.vue
  src/components/__tests__/IssueSearchAdvanced.spec.ts
  src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap
  src/composables/useSearchParams.ts
  src/views/FlawSearchView.vue
Labels: enhancement

#431 🐛 Remove unsupported mitigation ordering field
  src/components/IssueSearchAdvanced.vue
  src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap
Labels: bug, internal

#428 OSIDB-3453: Add new tooltips for truncated fields
  CHANGELOG.md
  src/components/FlawAffects.vue
  src/components/FlawTrackers.vue
  src/components/__tests__/FlawAffects.spec.ts
  src/components/__tests__/FlawTrackers.spec.ts
  src/components/__tests__/__snapshots__/FlawAffects.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawTrackers.spec.ts.snap
Labels: enhancement

#424 add test case: update affect
  features/common_utils.py
  features/flaw_detail_embargo.feature
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
  features/steps/flaw_list.py
  features/utils.py
Labels: QE

#435 🐛 OSIDB-3475: Add missing string on field emptiness search
  src/composables/useFlawsFetching.ts
Labels: bug

#432 🔥 OSIDB-3388: Remove irrelevant sorting fields
  src/components/IssueSearchAdvanced.vue
  src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap
Labels: internal

#437 🐛 OSIDB-3474: Dont populate trackers table on new affects
  CHANGELOG.md
  src/components/FlawAffects.vue
Labels: bug, enhancement

#436 add case:Bulk update affects
  features/flaw_detail_public.feature
  features/pages/base.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#439 📝 2024.9.2 release update
  CHANGELOG.md
Labels: internal

#442 add case:Customize affects pagination number
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE
