Repository RedHatProductSecurity/osim, pull requests merged in 2024-05, with the labels that each got.

#172 ✨ OSIDB-1204 Create CVSSv3 calculator
  .git-blame-ignore-revs
  CHANGELOG.md
  src/components/CvssCalculator.vue
  src/components/FlawForm.vue
  src/components/__tests__/CvssCalculator.spec.ts
  src/components/__tests__/FlawForm.spec.ts
  src/components/widgets/LabelStatic.vue
  src/composables/useCvssCalculator.ts
Labels: enhancement, requires huddle

#187 ♻️ OSIDB 1596: Unembargo confirmation on save flaw
  CHANGELOG.md
  src/components/FlawForm.vue
  src/components/IssueFieldEmbargo.vue
  src/composables/useFlawModel.ts
  src/views/FlawEditView.vue
Labels: enhancement

#180 Add test cases for update affects
  features/flaw_detail.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#204 Add test case for deleting affect
  features/flaw_detail.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#202 OSIM qe:Change reference and acknowledgements related case, use relat…
  features/pages/base.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_create.py
  features/steps/flaw_detail.py
Labels: QE

#205 Fix: Attributions form bugs
  CHANGELOG.md
  src/components/FlawForm.vue
  src/components/widgets/EditableList.vue
  src/composables/useFlawAttributionsModel.ts
  src/composables/useFlawModel.ts
Labels: bug

#212 Fix: Use object-specific updated_dt
  src/services/FlawService.ts
  src/utils/helpers.ts
Labels: bug

#210 Add test case for recover affect from deleting
  features/flaw_detail.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#228 OSIM qe:add case make flaw public and add public date
  features/flaw_detail.feature
  features/pages/base.py
  features/pages/flaw_create_page.py
  features/pages/flaw_detail_page.py
  features/steps/flaw_create.py
  features/steps/flaw_detail.py
  features/utils.py
Labels: QE
