Repository RedHatProductSecurity/osim, pull requests merged in 2024-11, with the labels that each got.

#474 📝 Update changelog for release
  CHANGELOG.md
Labels: internal

#473 🐛 OSIDB-3645: Use 24h format on history dates
  CHANGELOG.md
  src/components/__tests__/FlawHistory.spec.ts
  src/components/__tests__/__snapshots__/FlawHistory.spec.ts.snap
  src/utils/helpers.ts
Labels: bug

#466 OSIDB-3137: Allow multiple user saved searches
  CHANGELOG.md
  src/components/IssueQueue.vue
  src/components/IssueSearchAdvanced.vue
  src/components/__tests__/IssueQueue.spec.ts
  src/components/__tests__/IssueSearchAdvanced.spec.ts
  src/components/__tests__/Navbar.spec.ts
  src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap
  src/composables/useSearchParams.ts
  src/stores/SearchStore.ts
  src/stores/__tests__/SearchStore.spec.ts
  src/views/FlawSearchView.vue
  src/views/IndexView.vue
  src/views/__tests__/FlawSearchView.spec.ts
  src/views/__tests__/IndexView.spec.ts
  src/views/__tests__/__snapshots__/FlawSearchView.spec.ts.snap
  src/views/__tests__/__snapshots__/IndexView.spec.ts.snap
Labels: enhancement

#471 ✨ OSIDB-3563: History pagination
  CHANGELOG.md
  src/components/FlawForm.vue
  src/components/FlawHistory.vue
  src/components/__tests__/FlawHistory.spec.ts
  src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawHistory.spec.ts.snap
  src/components/widgets/LabelCollapsible.vue
Labels: enhancement

#443 ✨ OSIDB-3434: Reusable CvssCalculator for affect fields
  CHANGELOG.md
  src/components/CvssCalculator.vue
  src/components/CvssCalculator/CvssCalculator.vue
  src/components/CvssCalculator/CvssCalculatorOverlayed.vue
  src/components/CvssCalculator/CvssFactorButtons.vue
  src/components/CvssCalculator/CvssVectorInput.vue
  src/components/CvssSection.vue
  src/components/FlawAffects/FlawAffects.vue
  src/components/FlawAffects/FlawAffectsTable.vue
  src/components/FlawAffects/FlawAffectsTableRow.vue
  src/components/FlawAffects/__tests__/__snapshots__/FlawAffects.spec.ts.snap
  src/components/FlawForm.vue
  src/components/FlawTrackers.vue
  src/components/__tests__/CvssCalculator.spec.ts
  src/components/__tests__/CvssCalculatorOverlayed.spec.ts
  src/components/__tests__/FlawForm.spec.ts
  src/components/__tests__/__snapshots__/CvssCalculatorOverlayed.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawAffects.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawTrackers.spec.ts.snap
  src/composables/useCvssCalculator.ts
  src/composables/useFlawAffectsModel.ts
  src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Labels: enhancement

#480 add integration test: File trackers for individual affect
  features/README.md
  features/common_utils.py
  features/constants.py
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
  features/utils.py
Labels: QE

#482 add integration test case: File trackers for selected affects in a flaw
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#485 📝 Release 2024.11.1
  CHANGELOG.md
Labels: internal

#487 🐛 OSIDB-3658: Fix incorrect CVSS displays
  CHANGELOG.md
  src/components/CvssSection/CvssSection.vue
  src/views/__tests__/FlawCreateView.spec.ts
Labels: bug

#492 Configure Dependabot to add internal label
  .github/dependabot.yml
Labels: internal

#489 add intgration test case: Select/Deselect all trackers in tracker manager
  features/flaw_detail_public.feature
  features/pages/flaw_detail_page.py
  features/steps/flaw_detail.py
Labels: QE

#488 🐛 OSIDB-3720: Fix trackers status filtering
  CHANGELOG.md
  src/components/FlawTrackers/FlawTrackers.vue
  src/components/__tests__/FlawTrackers.spec.ts
Labels: bug

#502 Upgrade some dependencies to more recent minor versions to address vulnerabilities
  yarn.lock
Labels: dependencies

#505 Disable Dependabot version updates
  .github/dependabot.yml
Labels: internal
