Repository RedHatProductSecurity/osim, pull requests merged in 2025-06, with the labels that each got.

#570 ✨ Comments section display modes
  CHANGELOG.md
  src/components/FlawComments/CommentList.vue
  src/components/FlawComments/CommentsToolbar.vue
  src/components/FlawComments/FlawComments.vue
  src/components/FlawComments/NewCommentForm.vue
  src/components/FlawForm/FlawForm.vue
  src/components/__tests__/FlawComments.spec.ts
  src/components/__tests__/__snapshots__/FlawComments.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap
  src/composables/__tests__/useFlawCommentsModel.spec.ts
  src/composables/useFlawCommentsModel.ts
  src/constants/index.ts
  src/stores/SettingsStore.ts
  src/stores/__tests__/SettingsStore.spec.ts
  src/types/zodFlaw.ts
  src/utils/helpers.ts
  src/widgets/Tabs/Tabs.vue
Labels: enhancement

#575 🔥 Remove deprecated local build files
  build/entrypoint.d/30-local-proxy.sh.disabled
  local.Dockerfile
  scripts/run-local.sh
Labels: internal

#579 📦 Use fetch on generated client
  openapi.yml
  openapitools.json
  package.json
  src/generated-client/.gitignore
  src/generated-client/.npmignore
  src/generated-client/.openapi-generator-ignore
  src/generated-client/.openapi-generator/FILES
  src/generated-client/base.ts
  src/generated-client/common.ts
  src/generated-client/configuration.ts
  src/generated-client/git_push.sh
  src/generated-client/index.ts
  src/generated-client/models/index.ts
Labels: config, internal

#582 Update yarn lock file
  yarn.lock
Labels: internal
