Repository RedHatProductSecurity/osim, pull requests merged in 2025-01, with the labels that each got.

#517 🐛 Fix affects impact and resolution ordering
  CHANGELOG.md
  src/components/FlawAffects/__tests__/FlawAffects.spec.ts
  src/components/FlawAffects/useFilterSortAffects.ts
Labels: bug

#524 🐛 Mitre reverse proxy fix: Add missing character
  build/entrypoint.d/32-mitre-proxy.sh
Labels: bug, internal

#526 [OSIDB-3861] CVSS embargoed status does not match Flaw
  CHANGELOG.md
  src/composables/__tests__/useFlawCvssScores.spec.ts
  src/composables/useFlawCvssScores.ts
  src/services/FlawService.ts
Labels: bug

#527 ✨ Show all affects button
  CHANGELOG.md
  src/components/FlawAffects/FlawAffects.vue
  src/components/FlawAffects/__tests__/FlawAffects.spec.ts
  src/components/FlawAffects/__tests__/__snapshots__/FlawAffects.spec.ts.snap
  src/components/FlawAffects/flawAffectConstants.ts
  src/components/FlawTrackers/FlawTrackers.vue
  src/components/__tests__/FlawTrackers.spec.ts
  src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap
  src/components/__tests__/__snapshots__/FlawTrackers.spec.ts.snap
Labels: enhancement
